### ISSUE TITLE
ll command is not working in ubuntu.

### ISSUE THREAD

**Issue by DrudgeRajen** [alrra/dotfiles#16]
ll command is not working in ubuntu. And shell becomes to much slow when terminal is open.How it can be uninstalled ?I think user will need that information too .

**Comment by alrra** [comment]
> ll command is not working in ubuntu. 

@DrudgeRajen `ll` is just an [alias for `ls -l`](https://github.com/alrra/dotfiles/blob/7d3de6958554da34b19402ddd771cd028d552601/shell/bash_aliases#L23), so [it should work](http://manpages.ubuntu.com/manpages/hardy/man1/ls.1.html) on Ubuntu. 

> How it can be uninstalled 

Just remove [this line](https://github.com/alrra/dotfiles/blob/7d3de6958554da34b19402ddd771cd028d552601/shell/bash_aliases#L23).

**Comment by DrudgeRajen** [comment]
@alrra But why it is too much slow when terminal is open for first time ??

**Comment by alrra** [comment]
> But why it is too much slow when terminal is open for first time ?? 

@DrudgeRajen You haven't told me anything about your environment, so it's difficult for me to even start to guess what the problem might be.

Last time I checked, everything worked fine (I was using Ubuntu 15.10). If you find an issue that I can reproduce or find what is causing your problem, let me know. :)

**Comment by DrudgeRajen** [comment]
@alrra  I am using ubuntu 14.04 LTS . The problem is when i open the laptop and open shell/terminal i cannot do anything for some time(about 15-30min) because it doesn't load shell i think . I just see the cursor. And same problem when i open new terminal or add new tab in the terminal .
![terminalissue](https://cloud.githubusercontent.com/assets/4613510/12114921/25d8af36-b3d6-11e5-91a7-40f5028c1b55.png)

**Comment by DrudgeRajen** [comment]
@alrra I am using ubuntu 14.04 LTS . The problem is when i open the laptop and open shell/terminal i cannot do anything for some time(about 15-30min) because it doesn't load shell i think . I just see the cursor. And same problem when i open new terminal or add new tab in the terminal .

**Comment by alrra** [comment]
@DrudgeRajen Remove `~/.bashrc`, and let me know if the problem persists. :)

**Comment by DrudgeRajen** [comment]
@alrra Thank you it uninstall successfully :+1:
