### ISSUE TITLE
Move `get-content-encoding` to its own repository/project

### ISSUE THREAD

**Issue by mathiasbynens** [alrra/dotfiles#18]
https://github.com/alrra/dotfiles/blob/master/bin/get-content-encoding

You could use npm or Homebrew to let people install it globally with ease.

Same goes for `get-compression-heatmap`.

**Comment by alrra** [comment]
> You could use npm 

Maybe at some point in the future.

**Comment by alrra** [comment]
I've [removed `get-content-encoding` script](https://github.com/alrra/dotfiles/commit/7b0c9688ace334f2eb578b3cc7a989c951740e66) as I recently implemented the [`http-compression` rule ](https://sonarwhal.com/docs/user-guide/rules/http-compression/) for [`sonarwhal`](https://sonarwhal.com/), and it basically encapsulates the functionality of the script.
