### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by lordgreg** [alrra/dotfiles#29]
My question is, if you'd like to bring it on the clear stand (aka uninstall it)... what is the best way to do so?

**Comment by alrra** [comment]
@lordgreg First of all, from [`README.md`](https://github.com/alrra/dotfiles/blob/754a4aff5d4885c8b70e4be5e840d3902284dbf4/README.md#setup):

![](https://cloud.githubusercontent.com/assets/1223565/17380531/500e400e-59d0-11e6-94d3-98ae27af7cb0.png)

--

>  if you'd like to bring it on the clear stand (aka uninstall it)... what is the best way to do so?

Once you've run the setup script it's very hard (not impossible I guess...) to do that.

If you just want your terminal to basically go to a clean slate, just comment out the content from `~/.bash_profile`, or remove that file altogether.
