### ISSUE TITLE
Bash 4 Not Default

### ISSUE THREAD

**Issue by SkydiverFL** [alrra/dotfiles#31]
Bash 4 IS being installed.  The install script shows `Bash (use latest version)` is successful however Bash 4 does not remain the default.  The `shells` file lists the new version and the `$PATH` is set properly.  However, I'm having to manually execute `chsh -s $(brew --prefix)/bin/bash` to set it.

Any idea where to start?  The `bash.sh` script is logical and the flow appears to be correct.

**Comment by alrra** [comment]
@SkydiverFL Thanks for opening this issue!

**Comment by alrra** [comment]
@SkydiverFL This should be fixed by 8e01a24fcd98066e76d0ed16f6d04dce16a9bfe9.
