### ISSUE TITLE
GPG Missing

### ISSUE THREAD

**Issue by SkydiverFL** [alrra/dotfiles#32]
Your gitconfig has `gpsign = true` however GPG isn't included in the installs.  Which is incorrrect... the setting or GPG not being installed?  On a similar note, which GPG client would you recommend for osx?

**Comment by alrra** [comment]
> however GPG isn't included in the installs.

@SkydiverFL Yes, that's because I didn't get to writing a script for that part yet.

>  On a similar note, which GPG client would you recommend for osx?

My current local macOS setup is something similar to what is written here: https://github.com/pstadler/keybase-gpg-github.
