### ISSUE TITLE
Hide Terminal line marks

### ISSUE THREAD

**Issue by alrra** [alrra/dotfiles#36]
![macOS Terminal with line marks](https://cloud.githubusercontent.com/assets/1223565/19521987/4f23ea10-961e-11e6-9373-e42945d13e39.png)

The `Terminal` line marks can be hidden by running: 

```bash
defaults write com.apple.Terminal ShowLineMarks -int 0
```

| Before | After |
|:---:|:---:|
| <img src="https://cloud.githubusercontent.com/assets/1223565/19520835/407b51e6-961a-11e6-92ab-5022e75c3575.gif" alt="macOS Terminal with line marks"> | <img src="https://cloud.githubusercontent.com/assets/1223565/19520834/40753784-961a-11e6-8543-711461ff43cb.gif" alt="macOS Terminal without line marks"> |

**Comment by SkydiverFL** [comment]
That looks vaguely similar to the issue I'm having with several terminal utilities.  Many utilities, like Gulp, output text in a color that is not compatible with the theme.  The text ends up being the same color as the background and, therefore, is not visible.

**Comment by alrra** [comment]
@SkydiverFL I don't think your issue has anything to do with the line marks (see also: http://apple.stackexchange.com/a/209907). 

The only reason why I made this change was because I find the line marks really annoying.
