### ISSUE TITLE
Detect VM Guest

### ISSUE THREAD

**Issue by SkydiverFL** [alrra/dotfiles#37]
I've been looking at `dmidecode` to determine if the machine is a VM.  This would allow me to NOT install certain apps.  Do you already have a method for doing this?  If not, would you have any interest in adding it?

[Link to question on StackExchange](http://unix.stackexchange.com/questions/89714/easy-way-to-determine-virtualization-technology)

**Comment by alrra** [comment]
> Do you already have a method for doing this? 

@SkydiverFL Besides detecting the environment, you could make use of a flag (e.g.: `--vm`) or an environment variable. Or, if you want something more manual, you could just prompt the user for certain installs.

> If not, would you have any interest in adding it?

No, as that is not a use case for me.
