### ISSUE TITLE
Cannot move between words in the command line using `ctrl` + ←/→

### ISSUE THREAD

**Issue by llstarscreamll** [alrra/dotfiles#38]
Hi,

After install, I can only move between words on command line by pressing "alt+b" or "alt+f", how to get the default behavior? I mean  "ctrl+←" and "ctrl+→". I'm on Ubuntu 16.04.

Thanks for your effort on this project!!

**Comment by alrra** [comment]
> how to get the default behavior? 

@llstarscreamll You can either:

* Remove the `~/.inputrc` file (and [this line](https://github.com/alrra/dotfiles/blob/9a21351e304fa3df09e58433e4e3985639004b17/src/os/create_symbolic_links.sh#L22)).

* Add the following to your `~/.inputrc` file:

  ``` bash
  # Mappings for Ctrl-left-arrow and Ctrl-right-arrow for word moving

  "\e[1;5C": forward-word
  "\e[1;5D": backward-word
  "\e[5C": forward-word
  "\e[5D": backward-word
  "\e\e[C": forward-word
  "\e\e[D": backward-word
  ```

  (the above is taken from `/etc/inputrc`)

**Comment by SkydiverFL** [comment]
Thanks, @alrra & @llstarscreamll .  This has bugged me for a while... just hadn't had the time to deal with it.  I guess good things come to those who wait.  :)

**Comment by llstarscreamll** [comment]
@alrra thank you so much!!

**Comment by matthewharwood** [comment]
Might I ask why these lines arn't in the default inputrc
```
"\e[1;5C": forward-word
"\e[1;5D": backward-word
"\e[5C": forward-word
"\e[5D": backward-word
"\e\e[C": forward-word
"\e\e[D": backward-word
```
As they are needed for Iterm?
