### ISSUE TITLE
Linux Mint ?

### ISSUE THREAD

**Issue by SkydiverFL** [alrra/dotfiles#40]
Any plans to tweak the dotfiles for Linux Mint or another distro?  If so, which distros and when?

**Comment by alrra** [comment]
> Any plans to tweak the dotfiles for Linux Mint or another distro? If so, which distros and when?

@SkydiverFL No, and no plans in the near future. However, most things should work with other Linux distributions.

**Comment by SkydiverFL** [comment]
Just tweaked them for Linux Mint.  I have `mint` folders parallel to the original `ubuntu` folders.  Any interest to incorporate them?  I'd be happy to submit a pull request.  Just say the word.

BTW: Thanks for such polished files.

**Comment by alrra** [comment]
> Any interest to incorporate them? 

Thank you, but I don't use `Mint`. 

> Thanks for such polished files.

@SkydiverFL Glad you found them useful!
