### ISSUE TITLE
Optionally spawning private dotfiles install?

### ISSUE THREAD

**Issue by FredLackeyOfficial** [alrra/dotfiles#41]
I am considering adding a section to optionally spawn an install for a smaller section of scripts from a private git repo... or maybe multiple (private hosts file, restore app preferences, etc.).  The user would need to be prompted for credentials of that repo IF they wanted to install them.  Where / how would you suggest adding them?

**Comment by alrra** [comment]
>Where / how would you suggest adding them?

Something similar to [this](https://github.com/alrra/dotfiles/blob/a862e9e9c94670a50496ecba56fe5a2e30f2f88a/src/os/set_github_ssh_key.sh), I guess?
