### ISSUE TITLE
Thoughts on Mac App Store command line interface

### ISSUE THREAD

**Issue by SkydiverFL** [alrra/dotfiles#44]
Any chance you'd want to incorporate the Mac App Store command line interface?

Mac App Store command line interface
https://github.com/mas-cli/mas

**Comment by alrra** [comment]
@SkydiverFL See: https://github.com/alrra/dotfiles/issues/35#issuecomment-254550538.

**Comment by SkydiverFL** [comment]
Ooof... sorry for not searching first.
