### ISSUE TITLE
Keyboard Remapping

### ISSUE THREAD

**Issue by SkydiverFL** [alrra/dotfiles#45]
Do you do any keyboard remapping for terminal?  If so, what do you use?  I generally remap CAPS_LOCK and I'm thinking about adding it to my fork.

For example:

    # ~/.Xmodmap
    clear lock
    clear control
    add control = Caps_Lock Control_L Control_R
    keycode 66 = Control_L Caps_Lock NoSymbol NoSymbol

Your thoughts?

**Comment by alrra** [comment]
> Do you do any keyboard remapping for terminal?

I do not. 

> Your thoughts?

If it makes you more productive, go for it.
