### ISSUE TITLE
ask for confimation before installing apps

### ISSUE THREAD

**Issue by cescoferraro** [alrra/dotfiles#46]
While developing, and when using the dotfiles in my university computer for example, I do not want/ cannot install the apps. Seems that it is the only thing it does not ask for confirmation, while also being the one that takes the most time

**Comment by alrra** [comment]
> I do not want/ cannot install the apps

@cescoferraro These `dotfiles` are optimized for my usage so, if you find them useful, my recommendation is to fork this repository, and change them to better suit your own needs.
