### ISSUE TITLE
After the install

### ISSUE THREAD

**Issue by AaronWharton** [alrra/dotfiles#47]
I followed the gif installation and then I don't quite understand the configuration(Sorry I am poor in English...). how can I change the background just like the picture you showed? Thanks for your replying.

**Comment by alrra** [comment]
@AaronWharton The code that does that:

* [macOS](https://github.com/alrra/dotfiles/blob/93114fd980a45b2c3aefa75e0d0e5459618593d6/src/os/preferences/macos/set_terminal_theme.applescript) (or you can just manually add [this theme](https://github.com/alrra/dotfiles/blob/93114fd980a45b2c3aefa75e0d0e5459618593d6/src/os/preferences/macos/Solarized%20Dark.terminal)). 
* [Ubuntu](https://github.com/alrra/dotfiles/blob/93114fd980a45b2c3aefa75e0d0e5459618593d6/src/os/preferences/ubuntu/terminal.sh#L13-L18)

> Sorry I am poor in English..

Don't worry about it.

**Comment by AaronWharton** [comment]
@alrra Sorry to reply so lately. That helped me a lot! Thank you again.
