### ISSUE TITLE
Errors with neocomplete

### ISSUE THREAD

**Issue by FredLackeyOfficial** [alrra/dotfiles#48]
Do you usually have issues with the `~/.cache` folder with neocomplete?  I've been seeing permissions errors, while using vim, ever since forking your dotfiles.  For some reason two of the folders are always owned by `root:root`.  I'm thinking about adding a finalization step to the dotfiles to tweak the permissions...

`sudo chown -R $USERNAME ~/.cache`

![screenshot from 2017-04-04 16-57-10](https://cloud.githubusercontent.com/assets/6161622/24678566/02633f00-1959-11e7-9e44-a77182518f33.png)

**Comment by alrra** [comment]
> Do you usually have issues with the ~/.cache folder with neocomplete?

Never had that problem neither on mac OS, nor Ubuntu.
