### ISSUE TITLE
Possible bug in `bash_colors` (Ubuntu)

### ISSUE THREAD

**Issue by ramlmn** [alrra/dotfiles#51]
Wouldn't lines [`L32-L36`](https://github.com/alrra/dotfiles/blob/0531c796922207df8f87ced7da717aa2cfb829ee/src/shell/colors/ubuntu/bash_colors#L32-L36) always replace the `LS_COLORS` exported above in Ubuntu? (if `/usr/bin/dircolors` exists)

**Comment by alrra** [comment]
Sorry for the late reply!

@ramlmn Wanna open a Pull Request?
