### ISSUE TITLE
tmux vi-copy unknown command

### ISSUE THREAD

**Issue by aleks-sidorenko** [alrra/dotfiles#55]
In new versions of tmux they changed the way how copy mode is done.

This commit [tmux/tmux@76d6d36](https://github.com/tmux/tmux/commit/76d6d3641f271be1756e41494960d96714e7ee58) reworks how copy-mode key tables works. -t emacs-copy and -t vi-copy are gone, and are roughly replaced with -Tcopy-mode and -Tcopy-mode-vi. There are other required changes in how these key bindings work (also summarized in the commit above), requiring the use of send-keys.

Here is the link of what needs to be done:
[HowTo](https://github.com/tmux/tmux/issues/754#issuecomment-297452143)

**Comment by alrra** [comment]
@aleks-sidorenko Do you want to open a pull request? Thanks!

**Comment by aleks-sidorenko** [comment]
Ok, I will do that soon

**Comment by alrra** [comment]
> Ok, I will do that soon

Great, thanks!

**Comment by aleks-sidorenko** [comment]
Done :) plz review
