### ISSUE TITLE
Travis CI build failures on OSX images due to sudo required

### ISSUE THREAD

**Issue by wingy3181** [alrra/dotfiles#59]
Just noticed by builds are failing and noticed yours are too

Travis CI images are supposed to provide passwordless sudo
(https://docs.travis-ci.com/user/reference/osx/)

Seems like an issue in TravisCI or did they lock the image up?

Was this on your radar at all?

Just curious if you have had a look yet or not..

Not able to find anything yet

**Comment by alrra** [comment]
> passwordless sudo

Yes, that doesn't seem to be the case anymore.

> Was this on your radar at all?

Yes, just didn't have time to look into it yet. :(
