### ISSUE TITLE
Does not work in docker ubuntu

### ISSUE THREAD

**Issue by dmk255** [alrra/dotfiles#60]
Thanks for setting up this repo! I'm interested in giving it a whirl but I don't want to affect my current setup. 

I'm not sure if you use docker much, but it's a regular part of my development cycle - especially when it comes to testing new things. Unfortunately, there are some assumptions on what packages exist in this repo such as `lsb-core`, `sudo`, `gsettings`, etc. That's not a huge problem I just thought I'd let you know. 

You may or may not find it useful to check that some of those exist and download them if you don't.

Steps to reproduce / fix
* Start a docker container: `docker run --rum -it ubuntu /bin/bash`
* `apt update`
* `apt install -y wget lsb-core` // Note - if you need to install lsb-core or the script will die on the `lsb_release`
* `bash -c "$(wget -qO - https://raw.github.com/alrra/dotfiles/master/src/os/setup.sh)"`

**Comment by alrra** [comment]
> I'm not sure if you use docker much

I used it a bit, but not for these dotfiles. 

>  Unfortunately, there are some assumptions on what packages exist in this repo such as lsb-core, sudo, gsettings, etc. That's not a huge problem I just thought I'd let you know.
> You may or may not find it useful to check that some of those exist and download them if you don't.

Pull requests that can make things better are always welcomed! 

That being said, in the last period I haven't been using Ubuntu, so some of that code may also be a bit outdated.

---

Going to close this, but like I said above, any improvements are more then welcomed!
