### ISSUE TITLE
Partial History Search Enabled

### ISSUE THREAD

**Issue by Naman-ntc** [alrra/dotfiles#62]
In my opinion [partial match + arrow key](https://askubuntu.com/questions/59846/bash-history-search-partial-up-arrow) comes pretty useful and would be a nice add on.
Apart from it [cycling on TAB completions](https://stackoverflow.com/questions/7179642/how-can-i-make-bash-tab-completion-behave-like-vim-tab-completion-and-cycle-thro) is also a really nice touch.

**Comment by alrra** [comment]
@Naman-ntc Wanna open a PR? Thanks!
