### ISSUE TITLE
Spinner is acting up

### ISSUE THREAD

**Issue by rugaard** [alrra/dotfiles#65]
First of I can't tell you enough how AWESOME your dotfiles are. They inspired me to start working on my own. So thank you!

I have encountered a weird thing, I won't call it a bug, since I might just be me, but whenever the spinner completes it outputs some of the code, before moving on:
```
[/] Xcode Command Line Tools[13]+  Done                    eval "$CMDS" >&/dev/null 2> "$TMP_FILE"
[✔] Xcode Command Line Tools
```

I've also attached a screenshot from my Terminal after running the script:
![skaermbillede 2018-10-31 kl 14 00 56](https://user-images.githubusercontent.com/179868/47789903-284db380-dd16-11e8-88ae-4a3632c52ce8.png)

Do you have any idea, why it acts up?

If it's any help, then I'm running the script via `bash` in `iTerm 2` on `macOS 10.13.6` (High Sierra).

And again, thank you so much for sharing your dotfiles! 🙏🏻

**Comment by alrra** [comment]
> ![skaermbillede 2018-10-31 kl 14 00 56](https://user-images.githubusercontent.com/179868/47789903-284db380-dd16-11e8-88ae-4a3632c52ce8.png)

Did you change anything in the original code? 

I see you have `>&/dev/null`, when the code in this repository is:

https://github.com/alrra/dotfiles/blob/0fd0a0ab86f776cba0f9128bf5937dfdc86f2b8f/src/os/utils.sh#L74-L76

**Comment by alrra** [comment]
> same line 

Yes.

>  Or tabs vs. spaces 

No.

@rugaard Can you copy the [original file](https://raw.githubusercontent.com/alrra/dotfiles/0fd0a0ab86f776cba0f9128bf5937dfdc86f2b8f/src/os/utils.sh) over your local file, try again, and let me know how it goes? Thanks!

**Comment by rugaard** [comment]
Just did and it still outputs the line, but now it has  jumped down below the spinner 😳
![skaermbillede 2018-10-31 kl 14 41 17](https://user-images.githubusercontent.com/179868/47791928-1e7a7f00-dd1b-11e8-9e30-bf341449d338.png)

And I don't understand why the number in the `[15]` keeps being different? 😏

**Comment by rugaard** [comment]
Okay, I definitely think there's is something wrong with my fork. I might have ruined it somewhere.

I tried your repo without any changes, completely original and it did not output the same error.

Sorry for being a newb. But thanks a lot for taking your time to reply! 🙏🏻

**Comment by alrra** [comment]
> But thanks a lot for taking your time to reply! 🙏🏻

@rugaard  If you find out what caused it, let me know!

**Comment by rugaard** [comment]
Okay, I figured it out. But I can't explain the reason behind it. Maybe it more sense to you.  All I know it's based on me being a newb and not knowing when to use the correct comands.

So in your version of the repository you're "executing" your install scripts like this:
```
./create_directory.sh
```

And I was for some reason doing this:
```
. "./create_directory.sh"
```

I can't remember why I'm doing it like that. I think I've probably learned that's the correct way to execute files in some tutorial or screencast 😏
