### ISSUE TITLE
this commands possible?

### ISSUE THREAD

**Issue by sauio** [alrra/dotfiles#66]
Hi, is it possible to do script for this settings? i search hard bud cant find

"Finder: items in the sidebar"
show Mac
hide iCloud/recents
defaults write com.apple.finder ShowRecentTags -bool false

"Settings-general-RecentItems - NONE"
"set F13(printScr) for save-screenshot-as-file"
"set Alt+F13(printScr) for save-pic-of-area-as-file"
"Mojave Settings-Update -ALL disable"

**Comment by alrra** [comment]
@sauio You may be able to do that using [AppleScript](https://en.wikipedia.org/wiki/AppleScript)?

---

I'm going to close this issue as this issue tracker is for issues related to the code in this repository.

**Comment by sauio** [comment]
i cant write scripts, i just looking for if we can do it all same way as this one
defaults write com.apple.finder ShowRecentTags -bool false
but if you cant help me its ok, but sad :(
