### ISSUE TITLE
Homebrew formulae for firefox channels are not upto date

### ISSUE THREAD

**Issue by keyurgolanins** [alrra/dotfiles#67]
Homebrew formulae for firefox channels are not upto date.

The formula for `firefoxdeveloperedition` and `firefoxnightly` have been changed to `firefox-developer-edition` and `firefox-nightly`

**Comment by alrra** [comment]
@keyurgolanins Good catch! Want to open a PR? Thanks!

**Comment by keyurgolanins** [comment]
Hey Alrra,

Thanks. I already opened a PR with my personal GitHub.

Thanks

**Comment by alrra** [comment]
Thank you, @keyurgolani!

**Comment by keyurgolani** [comment]
Anytime @alrra
