### ISSUE TITLE
fixubuntu.sh is no more

### ISSUE THREAD

**Issue by brendan-R** [alrra/dotfiles#7]
This repo is a superb resource for Ubuntu users trying to get their dotfiles in order - thanks!

Just a note: I've noticed that [`https://fixubuntu.com/fixubuntu.sh`](https://fixubuntu.com/fixubuntu.sh) which is [used for setting preferences](https://github.com/alrra/dotfiles/blob/9d454a4e0fdda83506b3b1f4c34b2a0eab16a9ce/os/ubuntu/set_preferences.sh#L13), is no more.

It looks like the maintainers of the site have moved to a [GUI approach](https://github.com/micahflee/fixubuntu/issues/44), which is probably the right thing for most users, but quite annoying for a dotfiles repo.

**Comment by alrra** [comment]
> This repo is a superb resource for Ubuntu users trying to get their dotfiles in order - thanks!

@brendan-R Thanks for the kind words!

> I've noticed that https://fixubuntu.com/fixubuntu.sh which is used for setting preferences, is no more.

@brendan-R Thanks for the heads up! I'll look into it over the weekend. :)
