### ISSUE TITLE
get_os_version() Ubuntu update

### ISSUE THREAD

**Issue by virgilwashere** [alrra/dotfiles#73]
https://github.com/alrra/dotfiles/blob/eaeecbc9e6c8c0911bc5961df81f79330a4c6578/src/os/utils.sh#L150

In `get_os_version()`, the Ubuntu version can be easily returned with: `lsb_release -sr`. 
Or `lsb_release --short --release` if you prefer.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
$ lsb_release -sr
18.04
```

**Comment by alrra** [comment]
@virgilwashere Want to open a PR? Thanks!

**Comment by alrra** [comment]
Thank you, @virgilwashere!
