### ISSUE TITLE
Soft link or stow for syncing the dotfiles

### ISSUE THREAD

**Issue by wyq977** [alrra/dotfiles#80]
Hi thx a lot for sharing your config! It is one of the most aesthetically pleasing dotfiles I've come across on GitHub, even the output are formatted well ! 

I came across [stow](https://www.gnu.org/software/stow/manual/stow.html) and I've seen great things about it when comparing it to simply soft linking `ln -s`.

I wonder if you have tried using stow and might switch to it in the future

Thx 😄

**Comment by alrra** [comment]
> Hi thx a lot for sharing your config! It is one of the most aesthetically pleasing dotfiles I've come across on GitHub, even the output are formatted well !

@wyq977 Thank you! 🙇‍♂️

> I came across stow and I've seen great things about it when comparing it to simply soft linking ln -s.

I didn't know about it so, thank you for bringing it up!

> I wonder if you have tried using stow and might switch to it in the future

I've played a little bit with it, and to be honest, I personally don't see much benefit. Plus, I prefer to have more control <sup>[1]</sup> then what `stow` provides.

---

<sup>[1]</sup> In a recent version they introduce the following which kind addresses a thing I want, but to me it still seems awkward compared to just using `ln`.

From https://lists.gnu.org/archive/html/info-stow/2019-06/msg00000.html:

> GNU Stow 2.3.0 released 
> 
> ...
> 
> 1 New features / changes in behaviour
> 
> 1.1 New --dotfiles option
> 
>  Enable special handling for "dotfiles" (files or folders whose name
>  begins with a period) in the package directory. If this option is
>  enabled, Stow will add a preprocessing step for each file or folder
>  whose name begins with "dot-", and replace the "dot-" prefix in the
>  name by a period (".").  This is useful when Stow is used to manage
>  collections of dotfiles, to avoid having a package directory full of
>  hidden files.
> 
>  For example, suppose we have a package containing two files,
>  stow/dot-bashrc and stow/dot-emacs.d/init.el.  With this option, Stow
>  will create symlinks from .bashrc to stow/dot-bashrc and from
>  .emacs.d/init.el to stow/dot-emacs.d/init.el.  Any other files, whose
>  name does not begin with "dot-", will be processed as usual.
