### ISSUE TITLE
Depreciation of brew cask install cause errors in brew_install >= 2.7.0

### ISSUE THREAD

**Issue by wyq977** [alrra/dotfiles#83]
In [2.6.0](https://brew.sh/2020/12/01/homebrew-2.6.0/), `brew cask install` still works despite a depreciation warning but in later [2.7.0](https://brew.sh/2020/12/21/homebrew-2.7.0/), this flavor of install has now been depreciated. If you run the [main.sh](https://github.com/alrra/dotfiles/blob/main/src/os/install/macos/main.sh) now: it will throw errors like these.

![Screen Shot 2020-12-30 at 5 39 59 PM](https://user-images.githubusercontent.com/27303600/103368554-1fa8c180-4ac8-11eb-8975-2a1b593e3934.png)

Now it can be simply fixed by removing "cask" in [`brew_install`](https://github.com/alrra/dotfiles/blob/main/src/os/install/macos/utils.sh#L8-L10) function but I guess there's a better way for this?

```bash
# error
brew_install "Chrome" "google-chrome" "homebrew/cask" "cask"

# remove CMD in brew_install
brew_install "Chrome" "google-chrome" "homebrew/cask"
```

BTW, since the installation of brew might change to /opt/ as the Apple Silicon Macs rolls out that might also be a consideration for the future though I wouldn't worried about it now since they still don't have a CI with Arm mac now so the stable version won't be out very soon.

Ref:
* [All brew cask commands have been deprecated in favour of brew commands (with --cask) when necessary](https://github.com/Homebrew/brew/pull/8899)
* [macOS Homebrew running natively on M1/Apple Silicon/ARM has partial functionality. We recommend installing into /opt/homebrew and forbid installing into /usr/local (to avoid clashing with the macOS Intel install and allow their usage side-by-side). We currently recommend running Homebrew using Intel emulation with Rosetta 2.](https://github.com/Homebrew/brew/pull/9117)

**Comment by alrra** [comment]
@wyq977 Thank you for taking the time to open this issue, I sincerely appreciate it!
