### ISSUE TITLE
Remove zsh warning on macOS

### ISSUE THREAD

**Issue by wyq977** [alrra/dotfiles#87]
Today when i try config with my new m1 mac, I found out that a deprecation warning on terminal:

To remove this, simply add below to `bash.local` or `bash_profile`

```bash
export BASH_SILENCE_DEPRECATION_WARNING=1
```

If this is mentioned, pls close it. Thx

**Comment by alrra** [comment]
@wyq977 Thank you for bringing this up and taking the time to open this issue!
