### ISSUE TITLE
How to read shortcuts for tmux panes

### ISSUE THREAD

**Issue by matthewharwood** [alrra/dotfiles#9]
I'm unable to understand the hotkeys to create a pane from Terminal using Tmux? I'm on OS X :)

Question: Could you please explain what I push to split the windows horizontally and vertically?
```
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# [ PREFIX + - ] Split window horizontally
bind - split-window -v

# [ PREFIX + | ] Split window vertically
bind | split-window -h

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# [ PREFIX + h/j/k/l ] Move from pane to pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
```

**Comment by alrra** [comment]
>  Could you please explain what I push to split the windows horizontally and vertically?

The [`PREFIX` is set to `ctrl + a`](https://github.com/alrra/dotfiles/blob/9156055d904eaf399cbfd5e19535bf33ba59db6f/shell/tmux.conf#L23), so to split the window:

* horizontally: `crtl` + `a` and then `-`
* vertically: `ctrl` + `a` and then `|`
