### ISSUE TITLE
Support Multiple Environments 

### ISSUE THREAD

**Issue by FredLackeyOfficial** [alrra/dotfiles#90]
Just curious if you may have any interest in supporting multiple environments.  For years I've used your repo as a baseline for mine.  The only difference is I use my tweaked version for WSL, server, desktop, VMs, containers, different distros, etc.  Wanted to see if you'd find this useful.  If so, I'd happily create a PR for the changes.  The end result would mean a growing set of `preferences` and `install` folders.  For example...

```bash
macos
mint-18-desk-pm
mint-18-desk-vm
ubuntu-16-desk-pm
ubuntu-16-desk-vm
ubuntu-16-svr-pm
ubuntu-16-svr-vm
ubuntu-16-svr-wsl
ubuntu-17-desk-pm
ubuntu-17-desk-vm
... etc.
```

**Comment by alrra** [comment]
> For years I've used your repo as a baseline for mine. 

@FredLackeyOfficial Glad you found it useful!

> Just curious if you may have any interest in supporting multiple environments..
> The end result would mean a growing set of preferences and install folders. For example...

I am not planning to support other OSes or very specific OS versions.
