### ISSUE TITLE
rm: illegal option

### ISSUE THREAD

**Issue by JosChavz** [alrra/dotfiles#92]
When trying to run the MacOS script, I get an error as:
```rm: illegal option -- -
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
```

Running on MacOS Big Sur 11.6.1

**Comment by alrra** [comment]
@JosChavz Thanks for opening this issue! 🙇‍♂️

The recent change that caused this should be now fixed by https://github.com/alrra/dotfiles/commit/3569730444f232f02cd148185a7cc8f783b19dd2.

**Comment by JosChavz** [comment]
Turns out `mkdir` is doing the same issue. Wow, how strange. When working on Monterrey OS, it used to work well. Perhaps it was due to the downgrade that I made?

**Comment by alrra** [comment]
> Turns out mkdir is doing the same issue. Wow, how strange. When working on Monterrey OS, it used to work well. Perhaps it was due to the downgrade that I made?

@JosChavz Should be now fixed! Let me know if you find anything else.

Again, thank you for letting me know!

**Comment by JosChavz** [comment]
All good now! Thank you!
