### ISSUE TITLE
Plans for M1 / M2 / Homebrew 3?

### ISSUE THREAD

**Issue by FredLackeyOfficial** [alrra/dotfiles#93]
Have you tested with Homebrew 3 or Apple silicon?  I just noticed the install path for Homebrew 3 is different and peeked my head into your repo to see how you dealt with it, but didn't notice any changes.

**Comment by alrra** [comment]
@FredLackeyOfficial I realized that some of the changes related to this discussion I only had locally. I since pushed them to GitHub.
