### ISSUE TITLE
Suggestion with brewfile and how to better maintain while syncing changes with upstream

### ISSUE THREAD

**Issue by wyq977** [alrra/dotfiles#95]
Hi love ur setup and have been using it.

Firstly,
I would like to make a small suggestion as to the homebrew packages installed.

Currently, you would have different scripts under install/macos to managing packages installed via brew.

Is it easier that you have a single `Brewfile` for installed software (including casks): like https://github.com/wyq977/homebrew_bundle while also saving the version info.

Secondly
I found it kind of un-organized the way I managed.

Just wondering it what is the best practice for me to use ur dotfiles as a basis?

On the one hand, I would love to just sync changes from ur repo. say vim plugins

But also, I would like to make some small changes which may result in conflicts.

Syncing and merging seems like the only way to go right?

Best

**Comment by alrra** [comment]
> Is it easier that you have a single Brewfile for installed software (including casks): like https://github.com/wyq977/homebrew_bundle while also saving the version info.

Link doesn't exist.

> you would have different scripts under install/macos to managing packages installed via brew.

There are benefits to doing that, maintainability is one of them (e.g.: I don't need to understand much about the overall code to figure out that everything related to installing and setting up VSCode on macOS is in this [1 file](https://github.com/alrra/dotfiles/blob/27811cdcbad8cb52ec1656953d418264ee561994/src/os/installs/macos/vscode.sh) - which I can quickly remove if I don't want). 

---


> Syncing and merging seems like the only way to go right?

@wyq977 Pretty much.

The main intent with this repository was always to have a way to run [1 line](https://github.com/alrra/dotfiles/tree/27811cdcbad8cb52ec1656953d418264ee561994#setup), that, with minimum interactions, would configure and set up the basic things I need.

That being said, I think the repository is structured in such a way that it allows other people to fork and quickly customize it based on their own needs. 

Most people usually don't change the overall structure and change things such as what apps/CLIs are installed. In those cases it should be pretty straightforward for one to fetch the new changes and cherry-pick the ones they want. However, if one deviates a lot from the structure the repository provides, I do think keeping the fork in sync would be more difficult but, at that point, they are building their own thing and maybe forking is not the way to go.
